name: test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: WaitExec-linux-amd64
          - os: macos-latest
            asset_name: WaitExec-macos-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Get version
        run: |
          echo "VERSION=$(cat ".github/build/version" | head -1 | tr -d [:space:])" >> $GITHUB_ENV

      - name: Build
        run: |
          CARGO_TARGET_DIR=./build_assets cargo build --all --release